open module com.mastfrog.bunyan.java.v2.local.cached.remote.sinks {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.bunyan.remote;
    requires transitive com.mastfrog.bunyan.java.v2;
    requires transitive com.mastfrog.log.structured.storage;
    requires transitive com.mastfrog.util.streams;
    requires java.logging;

}
