// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.bunyan.v2.mongodb.sink {
    exports com.mastfrog.bunyan.v2.mongodb.sink;

    // Sibling com.mastfrog/giulius-bunyan-java-v2-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius.bunyan.java.v2;

    // Sibling com.mastfrog/giulius-mongodb-async-3.0.0-dev
    requires com.mastfrog.giulius.mongodb.async;

    // Sibling com.mastfrog/giulius-mongodb-async-init-3.0.0-dev
    requires com.mastfrog.giulius.mongodb.async.init;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/giulius-tests-3.0.0-dev
    requires com.mastfrog.giulius.tests;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.time;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
