open module com.mastfrog.bunyan.java.v2 {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.bunyan.java.v2;
    exports com.otherpackage;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.fileformat;
    requires transitive com.mastfrog.util.function;
    requires transitive com.mastfrog.util.streams;
    requires transitive com.mastfrog.util.strings;
    requires transitive com.mastfrog.util.time;
    requires java.logging;

}
