// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.bunyan.java.v2 {
    exports com.mastfrog.giulius.bunyan.java.v2;

    // Sibling com.mastfrog/bunyan-java-v2-3.0.0-dev
    requires com.mastfrog.bunyan.java.v2;

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/jackson-3.0.0-dev
    requires com.mastfrog.jackson;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.util.function;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;
    provides com.mastfrog.jackson.JacksonConfigurer with
       com.mastfrog.giulius.bunyan.java.v2.JacksonConfig;

}
