open module com.mastfrog.giulius.bunyan.java.v2 {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.bunyan.java.v2;
    requires transitive com.mastfrog.bunyan.java.v2;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.jackson;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.preconditions;

}
