// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.bunyan.java.v2.local.cached.remote.sinks {
    exports com.mastfrog.bunyan.remote;

    // Sibling com.mastfrog/bunyan-java-v2-3.0.0-dev
    requires com.mastfrog.bunyan.java.v2;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/log-structured-storage-3.0.0-dev
    requires com.mastfrog.log.structured.storage;

    // Inferred from source scan
    requires com.mastfrog.misc;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-streams-3.0.0-dev
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.util.function;
    requires java.logging;

    // Inferred from test-source-scan
    requires transitive org.junit.jupiter.api;

}
