// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.bunyan.java.v2 {
    exports com.mastfrog.bunyan.java.v2;

    // Inferred from source scan
    requires com.mastfrog.abstractions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan

    // Sibling com.mastfrog/util-fileformat-3.0.0-dev
    requires com.mastfrog.fileformat;

    // Inferred from source scan

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;

    // Inferred from source scan

    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;

    // Inferred from source scan

    // Sibling com.mastfrog/util-function-3.0.0-dev
    requires com.mastfrog.util.function;

    // derived from com.fasterxml.jackson.core/jackson-databind-0.0.0-? in com/fasterxml/jackson/core/jackson-databind/2.9.9.3/jackson-databind-2.9.9.3.pom
    requires transitive jackson.databind;

}
