open module com.mastfrog.bunyan.v2.mongodb.sink {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.bunyan.v2.mongodb.sink;
    requires transitive com.mastfrog.giulius.bunyan.java.v2;
    requires transitive com.mastfrog.giulius.mongodb.async;
    requires transitive com.mastfrog.giulius.mongodb.async.init;
    requires transitive com.mastfrog.giulius.tests;

}
