// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.bunyan.v2 {
    exports com.mastfrog.acteur.bunyan;

    // Sibling com.mastfrog/acteur-3.0.0-dev
    requires com.mastfrog.acteur;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Sibling com.mastfrog/bunyan-java-v2-3.0.0-dev
    requires com.mastfrog.bunyan.java.v2;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/giulius-bunyan-java-v2-3.0.0-dev
    // Transitive detected by source scan
    requires com.mastfrog.giulius.bunyan.java.v2;

    // Sibling com.mastfrog/injection-reflection-indexer-3.0.0-dev:compile
    requires static com.mastfrog.injection.reflection.indexer;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.time;

}
