open module com.mastfrog.acteur.bunyan.v2 {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.bunyan;
    requires transitive com.mastfrog.acteur;
    requires transitive com.mastfrog.bunyan.java.v2;
    requires transitive com.mastfrog.giulius.bunyan.java.v2;
    requires transitive com.mastfrog.injection.reflection.indexer;

}
